swe_surnames = [
    "Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson", "Larsson", "Olsson", "Persson", "Svensson", "Gustafsson",
    "Pettersson", "Jonsson", "Jansson", "Hansson", "Bengtsson", "Magnusson", "Olofsson", "Danielsson", "Lindberg", "Lindström",
    "Lindqvist", "Lundberg", "Lundqvist", "Lundström", "Lundgren", "Lindholm", "Lindgren", "Lindblom", "Bergman", "Bergström",
    "Berglund", "Berggren", "Bergqvist", "Bergman", "Persson", "Larsson", "Karlsson", "Sjöberg", "Sjögren", "Sjöström", "Sjölund",
    "Sjöholm", "Sjöberg", "Sjödin", "Sjöqvist", "Sjöblom", "Sjöstrand", "Holmberg", "Holmgren", "Holmquist", "Holmström", "Holmberg",
    "Holmgren", "Holmquist", "Holmström", "Holm", "Norberg", "Norén", "Norlander", "Nordström", "Nordlund", "Nordqvist", "Nordgren",
    "Nordblom", "Nyberg", "Nyström", "Nyqvist", "Nygren", "Nyman", "Bergstedt", "Bergvall", "Bergsten", "Bergman", "Bergmark",
    "Forsberg", "Forsman", "Forslund", "Forsström", "Forsberg", "Forsman", "Forslund", "Forsström", "Forsell", "Svensson",
    "Sjöberg", "Johansson", "Gustafsson", "Persson", "Eriksson", "Larsson", "Nilsson", "Andersson", "Lindberg", "Lindström",
    "Lindqvist", "Lundberg", "Lundqvist", "Lundström", "Lundgren", "Johansson", "Jansson", "Sjöholm", "Sjödin", "Sjöqvist", "Sjöblom", "Sjöstrand", "Holmberg", "Holmgren", "Holmquist", "Holmström", "Holmberg",
    "Holmgren", "Holmquist", "Holmström", "Holm", "Norberg", "Norén", "Norlander", "Nordström", "Nordlund", "Nordqvist", "Nordgren",
    "Nordblom", "Nyberg", "Nyström", "Nyqvist", "Nygren", "Nyman", "Bergstedt", "Bergvall", "Bergsten", "Bergman", "Bergmark",
    "Forsberg", "Forsman", "Forslund", "Forsström", "Forsberg", "Forsman", "Forslund", "Forsström", "Forsell", "Svensson",
    "Jönsson", "Månsson", "Axelsson", "Björk", "Björklund", "Engström", "Eklund", "Fredriksson", "Gunnarsson", "Göransson",
    "Håkansson", "Hellström", "Henriksson", "Hermansson", "Isaksson", "Ivarsson", "Jacobsson", "Jakobsson", "Johanneson",
    "Jung", "Karlström", "Kjellberg", "Kristensson", "Kristiansson", "Lundin", "Lundqvist", "Löfgren", "Mattsson", "Moberg",
    "Mårtensson", "Nord", "Nordin", "Nordlund", "Nyqvist", "Olander", "Olsson", "Oscarsson", "Palm", "Palmqvist", "Persdotter",
    "Petersson", "Robertsson", "Rosenberg", "Samuelsson", "Sandberg", "Sjögren", "Ström", "Strömberg", "Sundberg", "Sundqvist",
    "Sundström", "Svensson", "Tornqvist", "Ullberg", "Viklund", "Wallin", "Wallner", "Werner", "Wiklund", "Wikström",
    "Åberg", "Åkerman", "Åkesson", "Öberg", "Öhman", "Östberg", "Östlund"
]

nor_surnames = [
    "Andersen", "Andreassen", "Arnesen", "Bakke", "Berg", "Berntsen", "Birkeland", "Bjørnstad", "Bjørnsen",
    "Brekke", "Carlsen", "Christensen", "Dahl", "Danielsen", "Eide", "Eriksen", "Evensen", "Fjeld", "Foss",
    "Fredriksen", "Gundersen", "Hagen", "Hansen", "Haugen", "Haugland", "Helgesen", "Henriksen", "Hermansen",
    "Holm", "Holmen", "Hovland", "Isaksen", "Iversen", "Jacobsen", "Jansen", "Johannessen", "Johansen",
    "Johnsen", "Jørgensen", "Karlsen", "Kaspersen", "Knutsen", "Kristensen", "Kristiansen", "Larsen", "Larsson",
    "Lien", "Lund", "Lunde", "Løken", "Madsen", "Magnussen", "Martinsen", "Mathisen", "Mikkelsen", "Moen",
    "Mortensen", "Myhre", "Nilsen", "Nilsson", "Nordberg", "Nordby", "Nygaard", "Olsen", "Olsson", "Paulsen",
    "Pedersen", "Pettersen", "Rasmussen", "Rønning", "Sandberg", "Sande", "Sandvik", "Sivertsen", "Solberg",
    "Solem", "Sørensen", "Strand", "Strøm", "Sunde", "Svendsen", "Thoresen", "Thorsen", "Torgersen", "Tveit",
    "Vik", "Viken", "Werner", "Wold", "Ødegaard", "Østby", "Østensen", "Østergaard", "Østrem", "Øyen", "Øygarden",
    "Aas", "Aase", "Aune", "Bache", "Baumann", "Bendiksen", "Benjamin", "Bergan", "Berge", "Bergersen", "Bergland",
    "Berglund", "Bergstrøm", "Bergsvik", "Bjerke", "Bjørge", "Bjørgen", "Bjørk", "Bjørke", "Bjørklund", "Bjørn",
    "Borge", "Borgersen", "Brekken", "Breivik", "Brevik", "Broch", "Brottveit", "Bruun", "Bråthen", "Dale", "Dalen",
    "Dalen", "Dalen", "Dahlberg", "Dale", "Dalen", "Dalgaard", "Dalheim", "Daling", "Dalland", "Dalseth", "Dalva",
    "Dame", "Dane", "Danielsen", "Dans", "Danser", "David", "Davidsen", "Davidsen", "Davidson", "Davis", "Dehn",
    "Ditlefsen", "Djønne", "Dokken", "Dokmo", "Dybdahl", "Dybvik", "Dyrhaug", "Dyrstad", "Dæhli", "Dørum", "Edvardsen", "Eggen",
    "Eggesvik", "Eggestøl", "Egner", "Eide", "Eidem", "Eikeland", "Eikemo", "Eilertsen", "Einarsen", "Eiriksen", "Ekeberg",
    "Ekeli", "Ekelund", "Eklund", "Elden", "Eliassen", "Ellingsen", "Ellingsrud", "Ellingsvåg", "Ellefsen", "Elstad",
    "Elverum", "Emilsen", "Endresen", "Eng", "Engan", "Engdahl", "Engebretsen", "Engel", "Engelbrektsson", "Engelstad",
    "Engen", "Enger", "Engeseth", "Englund", "Engstrøm", "Enoksen", "Ensrud", "Erlandsen", "Ervik", "Eskeland", "Evensen",
    "Evjen", "EØyen", "Fagerli", "Fagerlund", "Fagervik", "Falk", "Falkenberg", "Falkenberg", "Falkeid", "Falstad",
    "Fanuelsen", "Fauske", "Fekjær", "Fernandez", "Fidje", "Fidjeland", "Finstad", "Fiskerstrand", "Flaata", "Flaathe",
    "Flak", "Flaten", "Fleischer", "Flesland", "Flink", "Flint", "Flo", "Floberg", "Flom", "Flood", "Flø", "Flønes",
    "Foosnæs", "Fornes", "Forseth", "Foss", "Fossen", "Fossheim", "Fossum", "Fosså", "Frantzen", "Fredheim", "Fredriksen",
    "Fredvang", "Freng", "Frigstad", "Friis", "Frimannslund", "Frivoll", "Frøland", "Frøland", "Fugleberg", "Fure",
    "Furnes", "Furre", "Furseth", "Fuskeland", "Fyhn", "Fyllingen", "Fylkesnes", "Fyresdal", "Færøy", "Følstad", "Førde",
    "Gabrielsen", "Galtung", "Garmo", "Garvik", "Gaustad", "Gebhardt", "Geelmuyden", "Gehrken", "Gerdts", "Gibson",
    "Gilbert", "Gill", "Gjedrem", "Gjerde", "Gjernes", "Gjertsen", "Gjertsen", "Gjessing", "Gjettermann", "Gjønnes",
    "Gjørv", "Glad", "Glad", "Glendrange", "Gløersen", "Goksøyr", "Gran", "Granberg", "Granli", "Granlund", "Granly",
    "Grann", "Gravdal""Hagen", "Hansen", "Haugen", "Haugland", "Helgesen", "Henriksen", "Hermansen", "Holm", "Holmen", "Hovland",
    "Isaksen", "Iversen",    "Jacobsen", "Jansen", "Johannessen", "Johansen", "Johnsen", "Jørgensen", "Karlsen", "Kaspersen", "Knutsen",
    "Kristensen", "Kristiansen", "Larsen", "Larsson", "Lien", "Lund", "Lunde", "Løken", "Madsen", "Magnussen", "Martinsen",
    "Mathisen", "Mikkelsen", "Moen", "Mortensen", "Myhre", "Nilsen", "Nilsson", "Nordberg", "Nordby", "Nygaard", "Olsen", "Olsson", 
    "Paulsen", "Pedersen", "Pettersen", "Rasmussen", "Rønning", "Sandberg", "Sande", "Sandvik", "Sivertsen", "Solberg", "Solem", 
    "Sørensen", "Strand", "Strøm", "Sunde", "Svendsen", "Thoresen", "Thorsen", "Torgersen", "Tveit", "Vik", "Viken", "Werner", 
    "Wold", "Ødegaard", "Østby", "Østensen", "Østergaard", "Østrem", "Øyen", "Øygarden"]
    

swe_first_names = [
    {"name": "Elsa", "gender": "F"},
    {"name": "Alice", "gender": "F"},
    {"name": "Maja", "gender": "F"},
    {"name": "Ebba", "gender": "F"},
    {"name": "Olivia", "gender": "F"},
    {"name": "Astrid", "gender": "F"},
    {"name": "Alma", "gender": "F"},
    {"name": "Ella", "gender": "F"},
    {"name": "Wilma", "gender": "F"},
    {"name": "Klara", "gender": "F"},
    {"name": "Adel", "gender": "F"},
    {"name": "Saga", "gender": "F"},
    {"name": "Nellie", "gender": "F"},
    {"name": "Molly", "gender": "F"},
    {"name": "Nova", "gender": "F"},
    {"name": "Stella", "gender": "F"},
    {"name": "Elin", "gender": "F"},
    {"name": "Lilly", "gender": "F"},
    {"name": "Emilia", "gender": "F"},
    {"name": "Ellen", "gender": "F"},
    {"name": "Tilde", "gender": "F"},
    {"name": "Linnéa", "gender": "F"},
    {"name": "Liv", "gender": "F"},
    {"name": "Signe", "gender": "F"},
    {"name": "Ines", "gender": "F"},
    {"name": "Lea", "gender": "F"},
    {"name": "Tyra", "gender": "F"},
    {"name": "Sara", "gender": "F"},
    {"name": "Nora", "gender": "F"},
    {"name": "Moa", "gender": "F"},
    {"name": "Sofia", "gender": "F"},
    {"name": "Lovisa", "gender": "F"},
    {"name": "Elvira", "gender": "F"},
    {"name": "Alicia", "gender": "F"},
    {"name": "Meja", "gender": "F"},
    {"name": "Filippa", "gender": "F"},
    {"name": "Hanna", "gender": "F"},
    {"name": "Isabelle", "gender": "F"},
    {"name": "Ester", "gender": "F"},
    {"name": "Agnes", "gender": "F"},
    {"name": "Tilda", "gender": "F"},
    {"name": "Amanda", "gender": "F"},
    {"name": "Frida", "gender": "F"},
    {"name": "Evelina", "gender": "F"},
    {"name": "Cornelia", "gender": "F"},
    {"name": "Tove", "gender": "F"},
    {"name": "Vera", "gender": "F"},
    {"name": "Ronja", "gender": "F"},
    {"name": "Alva", "gender": "F"},
    {"name": "Nova", "gender": "F"},
    {"name": "Ida", "gender": "F"},
    {"name": "Lova", "gender": "F"},
    {"name": "Oscar", "gender": "M"},
    {"name": "Lucas", "gender": "M"},
    {"name": "William", "gender": "M"},
    {"name": "Elias", "gender": "M"},
    {"name": "Hugo", "gender": "M"},
    {"name": "Oliver", "gender": "M"},
    {"name": "Liam", "gender": "M"},
    {"name": "Noah", "gender": "M"},
    {"name": "Adam", "gender": "M"},
    {"name": "Alexander", "gender": "M"},
    {"name": "Filip", "gender": "M"},
    {"name": "Emil", "gender": "M"},
    {"name": "Viktor", "gender": "M"},
    {"name": "Theo", "gender": "M"},
    {"name": "Leo", "gender": "M"},
    {"name": "Albin", "gender": "M"},
    {"name": "Anton", "gender": "M"},
    {"name": "Isak", "gender": "M"},
    {"name": "Max", "gender": "M"},
    {"name": "Arvid", "gender": "M"},
    {"name": "Charlie", "gender": "M"},
    {"name": "Elliot", "gender": "M"},
    {"name": "Edvin", "gender": "M"},
    {"name": "Alfred", "gender": "M"},
    {"name": "Vincent", "gender": "M"},
    {"name": "Wilhelm", "gender": "M"},
    {"name": "Gabriel", "gender": "M"},
    {"name": "Edvard", "gender": "M"},
    {"name": "Gustav", "gender": "M"},
    {"name": "Samuel", "gender": "M"},
    {"name": "Isac", "gender": "M"},
    {"name": "Karl", "gender": "M"},
    {"name": "Joel", "gender": "M"},
    {"name": "Victor", "gender": "M"},
    {"name": "Axel", "gender": "M"},
    {"name": "Simon", "gender": "M"},
    {"name": "Melvin", "gender": "M"},
    {"name": "Benjamin", "gender": "M"},
    {"name": "Nils", "gender": "M"},
    {"name": "Rasmus", "gender": "M"},
    {"name": "Adrian", "gender": "M"},
    {"name": "Erik", "gender": "M"},
    {"name": "Matteo", "gender": "M"},
    {"name": "Daniel", "gender": "M"},
    {"name": "Jonathan", "gender": "M"},
    {"name": "Sixten", "gender": "M"},
    {"name": "Levi", "gender": "M"},
    {"name": "Emrik", "gender": "M"},
    {"name": "Milton", "gender": "M"},
    {"name": "Love", "gender": "M"},
    {"name": "Elton", "gender": "M"},
    {"name": "Sigge", "gender": "M"},
    {"name": "Elis", "gender": "M"}
    ]

nor_first_names = [
    {"name": "Emma", "gender": "F"},
    {"name": "Nora", "gender": "F"},
    {"name": "Sara", "gender": "F"},
    {"name": "Olivia", "gender": "F"},
    {"name": "Emilie", "gender": "F"},
    {"name": "Sophie", "gender": "F"},
    {"name": "Maja", "gender": "F"},
    {"name": "Ella", "gender": "F"},
    {"name": "Ida", "gender": "F"},
    {"name": "Ingrid", "gender": "F"},
    {"name": "Sofie", "gender": "F"},
    {"name": "Leah", "gender": "F"},
    {"name": "Frida", "gender": "F"},
    {"name": "Thea", "gender": "F"},
    {"name": "Emilia", "gender": "F"},
    {"name": "Julie", "gender": "F"},
    {"name": "Amalie", "gender": "F"},
    {"name": "Hanna", "gender": "F"},
    {"name": "Malin", "gender": "F"},
    {"name": "Tuva", "gender": "F"},
    {"name": "Victoria", "gender": "F"},
    {"name": "Mathilde", "gender": "F"},
    {"name": "Marie", "gender": "F"},
    {"name": "Hedda", "gender": "F"},
    {"name": "Aurora", "gender": "F"},
    {"name": "Maria", "gender": "F"},
    {"name": "Alma", "gender": "F"},
    {"name": "Eline", "gender": "F"},
    {"name": "Ada", "gender": "F"},
    {"name": "Oda", "gender": "F"},
    {"name": "Vilde", "gender": "F"},
    {"name": "Hannah", "gender": "F"},
    {"name": "Anna", "gender": "F"},
    {"name": "Alva", "gender": "F"},
    {"name": "Tiril", "gender": "F"},
    {"name": "Selma", "gender": "F"},
    {"name": "Isabella", "gender": "F"},
    {"name": "Eva", "gender": "F"},
    {"name": "Ingeborg", "gender": "F"},
    {"name": "Martine", "gender": "F"},
    {"name": "Sunniva", "gender": "F"},
    {"name": "Eline", "gender": "F"},
    {"name": "Andrea", "gender": "F"},
    {"name": "Nora", "gender": "F"},
    {"name": "Johanne", "gender": "F"},
    {"name": "Helene", "gender": "F"},
    {"name": "Guro", "gender": "F"},
    {"name": "Silje", "gender": "F"},
    {"name": "Sandra", "gender": "F"},
    {"name": "Karoline", "gender": "F"},
    {"name": "Linnea", "gender": "F"},
    {"name": "Lena", "gender": "F"},
    {"name": "Erik", "gender": "M"},
    {"name": "Jonas", "gender": "M"},
    {"name": "Liam", "gender": "M"},
    {"name": "Oscar", "gender": "M"},
    {"name": "Mathias", "gender": "M"},
    {"name": "Lucas", "gender": "M"},
    {"name": "Oliver", "gender": "M"},
    {"name": "Filip", "gender": "M"},
    {"name": "Noah", "gender": "M"},
    {"name": "Herman", "gender": "M"},
    {"name": "Emil", "gender": "M"},
    {"name": "William", "gender": "M"},
    {"name": "Kristian", "gender": "M"},
    {"name": "Andreas", "gender": "M"},
    {"name": "Benjamin", "gender": "M"},
    {"name": "Sander", "gender": "M"},
    {"name": "Alexander", "gender": "M"},
    {"name": "Johan", "gender": "M"},
    {"name": "Magnus", "gender": "M"},
    {"name": "Martin", "gender": "M"},
    {"name": "Henrik", "gender": "M"},
    {"name": "Thomas", "gender": "M"},
    {"name": "Marius", "gender": "M"},
    {"name": "Sebastian", "gender": "M"},
    {"name": "Daniel", "gender": "M"},
    {"name": "David", "gender": "M"},
    {"name": "Jon", "gender": "M"},
    {"name": "Fredrik", "gender": "M"},
    {"name": "Nikolai", "gender": "M"},
    {"name": "Joakim", "gender": "M"},
    {"name": "Simen", "gender": "M"},
    {"name": "Marcus", "gender": "M"},
    {"name": "Gustav", "gender": "M"},
    {"name": "Leo", "gender": "M"},
    {"name": "Viktor", "gender": "M"},
    {"name": "Øystein", "gender": "M"},
    {"name": "Peter", "gender": "M"},
    {"name": "Kasper", "gender": "M"},
    {"name": "Elias", "gender": "M"},
    {"name": "Kristoffer", "gender": "M"},
    {"name": "Henning", "gender": "M"},
    {"name": "Christoffer", "gender": "M"},
    {"name": "Bjørn", "gender": "M"},
    {"name": "Stian", "gender": "M"},
    {"name": "Jonathan", "gender": "M"},
    {"name": "Per", "gender": "M"},
    {"name": "Ole", "gender": "M"},
    {"name": "Tobias", "gender": "M"},
    {"name": "Rasmus", "gender": "M"},
    {"name": "Tor", "gender": "M"},
    {"name": "Simen", "gender": "M"},
    {"name": "Jonatan", "gender": "M"},
    {"name": "Robin", "gender": "M"}
    ]