import random_data as rd

country = rd.country_gen()
gender = rd.gender_gen()
name = rd.name_gen(gender,country['country_name'])
ssn = rd.ssn_gen(gender, country['country_name'])
postal_code = rd.postal_code_gen(country['country_name'])
phone_number = rd.phone_number_gen(country['country_name'])
requested_loan_amount = rd.requested_loan_amount_gen()
credit_score = rd.credit_score_gen()
loan_approved = rd.check_loan_approval(credit_score, requested_loan_amount)
date_of_request = rd.datetime_generator(2020)
product_id = rd.product_req_gen()
ip = rd.random_ip_gen()


print(country['country_name'])
print(gender)
print(name)
print(ssn)
print(postal_code)
print(phone_number)
print(requested_loan_amount)
print(credit_score)
print(loan_approved)
print(date_of_request)
print(product_id)
print(ip)