swe_surnames = [
    "Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson", "Larsson", "Olsson", "Persson", "Svensson", "Gustafsson",
    "Pettersson", "Jonsson", "Jansson", "Hansson", "Bengtsson", "Magnusson", "Olofsson", "Danielsson", "Lindberg", "Lindström",
    "Lindqvist", "Lundberg", "Lundqvist", "Lundström", "Lundgren", "Lindholm", "Lindgren", "Lindblom", "Bergman", "Bergström",
    "Berglund", "Berggren", "Bergqvist", "Bergman", "Persson", "Larsson", "Karlsson", "Sjöberg", "Sjögren", "Sjöström", "Sjölund",
    "Sjöholm", "Sjöberg", "Sjödin", "Sjöqvist", "Sjöblom", "Sjöstrand", "Holmberg", "Holmgren", "Holmquist", "Holmström", "Holmberg",
    "Holmgren", "Holmquist", "Holmström", "Holm", "Norberg", "Norén", "Norlander", "Nordström", "Nordlund", "Nordqvist", "Nordgren",
    "Nordblom", "Nyberg", "Nyström", "Nyqvist", "Nygren", "Nyman", "Bergstedt", "Bergvall", "Bergsten", "Bergman", "Bergmark",
    "Forsberg", "Forsman", "Forslund", "Forsström", "Forsberg", "Forsman", "Forslund", "Forsström", "Forsell", "Svensson",
    "Sjöberg", "Johansson", "Gustafsson", "Persson", "Eriksson", "Larsson", "Nilsson", "Andersson", "Lindberg", "Lindström",
    "Lindqvist", "Lundberg", "Lundqvist", "Lundström", "Lundgren", "Johansson", "Jansson", "Sjöholm", "Sjödin", "Sjöqvist", "Sjöblom", "Sjöstrand", "Holmberg", "Holmgren", "Holmquist", "Holmström", "Holmberg",
    "Holmgren", "Holmquist", "Holmström", "Holm", "Norberg", "Norén", "Norlander", "Nordström", "Nordlund", "Nordqvist", "Nordgren",
    "Nordblom", "Nyberg", "Nyström", "Nyqvist", "Nygren", "Nyman", "Bergstedt", "Bergvall", "Bergsten", "Bergman", "Bergmark",
    "Forsberg", "Forsman", "Forslund", "Forsström", "Forsberg", "Forsman", "Forslund", "Forsström", "Forsell", "Svensson",
    "Jönsson", "Månsson", "Axelsson", "Björk", "Björklund", "Engström", "Eklund", "Fredriksson", "Gunnarsson", "Göransson",
    "Håkansson", "Hellström", "Henriksson", "Hermansson", "Isaksson", "Ivarsson", "Jacobsson", "Jakobsson", "Johanneson",
    "Jung", "Karlström", "Kjellberg", "Kristensson", "Kristiansson", "Lundin", "Lundqvist", "Löfgren", "Mattsson", "Moberg",
    "Mårtensson", "Nord", "Nordin", "Nordlund", "Nyqvist", "Olander", "Olsson", "Oscarsson", "Palm", "Palmqvist", "Persdotter",
    "Petersson", "Robertsson", "Rosenberg", "Samuelsson", "Sandberg", "Sjögren", "Ström", "Strömberg", "Sundberg", "Sundqvist",
    "Sundström", "Svensson", "Tornqvist", "Ullberg", "Viklund", "Wallin", "Wallner", "Werner", "Wiklund", "Wikström",
    "Åberg", "Åkerman", "Åkesson", "Öberg", "Öhman", "Östberg", "Östlund"
]

swe_first_names = [
    "Emma", "Liam", "Olivia", "Noah", "Ava", "Isabella", "Sophia", "Mia", "Charlotte", "Amelia",
    "Harper", "Evelyn", "Liam", "Benjamin", "Henry", "Alexander", "Sebastian", "James", "Jack", "William",
    "Ella", "Lucas", "Michael", "Daniel", "Jacob", "Matthew", "Aiden", "Oliver", "Elijah", "Emily",
    "Daniel", "Julia", "David", "Andrew", "Emily", "Grace", "Lucas", "Gabriel", "Samuel", "Oscar",
    "Sophie", "Sofia", "Emilia", "Lucas", "Hugo", "Alice", "Alexander", "Maja", "Noah", "Lily",
    "Aiden", "Max", "Leo", "Elias", "Isabella", "Olivia", "Jacob", "Mia", "William", "Ella",
    "Oliver", "Sophia", "Lucas", "Elias", "Ava", "Liam", "Hannah", "Noah", "Emil", "Lily",
    "Emma", "Freja", "Ida", "Oscar", "Theo", "Felix", "Alma", "Anna", "Alfred", "Alexander",
    "Viktor", "Filip", "Ella", "Agnes", "Elliot", "Ebba", "William", "Molly", "Matilda", "Viggo",
    "Love", "Linnea", "Levi", "Wilma", "Maja", "Alma", "Lilly", "Ellen", "Elvira", "Charlie",
    "Louise", "Oliver", "Vilma", "Selma", "Nora", "Frans", "Erik", "Elisabeth", "Malthe", "Emma",
    "Frida", "Noah", "Luna", "Astrid", "Emil", "Vincent", "Noah", "Julia", "Melvin", "Albin",
    "Astrid", "Stella", "Nils", "Nathalie", "Oscar", "Linnea", "Elliot", "Filip", "Ebba", "Stella",
    "Vilhelm", "Alicia", "Isak", "Johan", "Sara", "Hanna", "Elsa", "Ester", "Olivia", "Edvin",
    "Tilda", "Ellie", "Ella", "Joline", "Casper", "Livia", "Jonathan", "Leah", "Malthe", "Lea",
    "John", "Nora", "Jonathan", "Ines", "Alfred", "Sofie", "Rasmus", "Sofia", "Julian", "Signe",
    "Rasmus", "Clara", "Anton", "Lovisa", "Mio", "Elise", "Albin", "Klara", "Milo", "Tilde",
    "Elina", "Milla", "Emilia", "Sandra", "Sander", "Nellie", "Loke", "Lea", "Aron", "Livia",
    "Vilda", "Isabelle", "Samuel", "Saga", "Frank", "Elin", "Adam"
]

